language: java
jdk:
- openjdk7
- oraclejdk7
- oraclejdk8
notifications:
  slack:
    secure: IlNoubmoUMK9PsG4NJGPEMlb/GczsELLlOCDeV5JQg/yPOtG8t3OEzDCAfIko2vTvVPvIBQnBy7rHcdu6kyHeJyjkkWMEDGEz6qMlS59DHiyH+K0VM5HBaCWW35DpugprgX+prWL3qEuCkYJKNGpY0R88SlBV39sfV36OvoVYDVef7VbVBQ3I8n3kQ0WlGzt8zZIDU0irRrA9xeZmrA4ShsD5A8PvU7zGWRjlk8FNtH4+UOJMa+pKwyC/iFpp25EYKrcEqgmm9rTBuElgo3IiKcX8yT5hKKB9UMgThhylfG5hqsWGGgd37VetelE1kmFjyFWDaGIYfVb/NJ2E7LwrLRv0JDFb+lmbWgxUjVwtWP7N/8jwOkVvhMl0S8Uiq1QF2fH5s6ibHDH+R0j7nYMdlmWMkrjPS+LzKyt/sbWghCq1HfK2LcHFVW5F5gkhkv4lTVzhw4GA55pd+dF2O067SGdznuF3tbI8WxBKaF51c1I8ruNoRtExuwQvgXiMUgh8imQbapcbqTFE7Nc02s/fCaSnqwqo5qun2wj0oxNPJOx2Dzscg5snjw4ngztXicPo9JquVTKFEPSmT6QV29j6UngEfHv7UecctyYVa4kvVUfOSTdeLyh08R/MqYlOdwuVG6qRLW0vI3Of7iLTqFVS5DNPAIRsFfwowSzNW1JWYo=
